# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Bmsm_filtered_cpp <- function(dat, A, gm, rhoe, sigma1, sigma2) {
    .Call('MSM_Bmsm_filtered_cpp', PACKAGE = 'MSM', dat, A, gm, rhoe, sigma1, sigma2)
}

Bmsm_stage2_ll_cpp <- function(dat, A, gm, rhoe, sigma1, sigma2) {
    .Call('MSM_Bmsm_stage2_ll_cpp', PACKAGE = 'MSM', dat, A, gm, rhoe, sigma1, sigma2)
}

Msm_likelihood_cpp <- function(pimat0, omegat, A) {
    .Call('MSM_Msm_likelihood_cpp', PACKAGE = 'MSM', pimat0, omegat, A)
}

Msm_ll_cpp <- function(pimat0, omegat, A) {
    .Call('MSM_Msm_ll_cpp', PACKAGE = 'MSM', pimat0, omegat, A)
}

Msm_smooth_cpp <- function(A, P) {
    .Call('MSM_Msm_smooth_cpp', PACKAGE = 'MSM', A, P)
}

